title: vblinden
email: hello@vblinden.nl
description: >- # this means to ignore newlines until "baseurl:"
  I go by the name of vblinden and I am a sofware engineer by trade. On my site you can find some thoughts and other babbling that I thought were important enough to put online.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vblinden
github_username:  vblinden
show_excerpts: true

# Build settings
# theme: minima
plugins:
  - jekyll-feed
