import 'app/globals.css';

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>vblinden.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="dark:bg-gray-700 dark:text-gray-300 bg-gray-50 font-serif antialiased">
        <div className="container mx-auto">
          <div className="mx-3">
            <div className="my-8">
              <h1 className="text-3xl font-bold mb-3 font-sans">
                <a href="/" className="hover:text-blue-600">
                  vblinden.
                </a>
              </h1>
            </div>

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
